---
title: "p8105_hw5_ly2496"
author: "Ling Yi"
date: "11/10/2020"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
	fig.width = 6, 
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```
Problem 1

```{r}
homicide_df = 
  read_csv("homicide_data/homicide-data.csv") %>% 
  mutate(
    city_state = str_c(city, state, sep = "_"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved", 
      disposition == "Open/No arrest"        ~ "unsolved", 
      disposition == "Closed by arrest"      ~ "solved",
    )
  ) %>% 
  select(city_state, resolved) %>% 
  filter(city_state != "Tulsa_AL")
```


```{r}
aggregate_df = 
  homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    hom_total = n(),
    hom_unsolved = sum(resolved == "unsolved")
  )
```

Can i do a prop tests for a single city?

```{r}
prop.test(
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_unsolved),      
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_total)) %>%
  broom::tidy()
```

Try to iterate........

```{r}
results_df=
  aggregate_df %>% 
  mutate(
    prop_tests = map2(.x = hom_unsolved, .y = hom_total, ~prop.test(x = .x, n = .y)),
    tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))
  ) %>% 
  select(-prop_tests) %>% 
  unnest(tidy_tests) %>% 
  select(city_state, estimate, conf.low, conf.high)
```


Take a look at the results data frame

```{r}
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate))+
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

##problem 2


```{r}

file_name = list.files(path = "./lda_data", full.names = TRUE)

study_df = 
  file_name %>% 
  set_names() %>% 
  map_dfr(read_csv, .id = "file")

study_tidy_df =
  study_df %>% 
  mutate(
  file = str_replace_all(file, "./lda_data/", ""),
  file = str_replace_all(file, ".csv", "")
  ) %>% 
  separate(file, into = c("group", "id"), sep = "_", remove = FALSE) %>% 
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    names_prefix = "week_", 
    values_to = "obs"
  ) %>% 
  mutate(
    obs = as.numeric(obs)
  )

study_tidy_df %>% 
ggplot(aes(x = week, y = obs, group = file)) + 
  geom_line(aes(color = group)) +
  labs(
    title = "Observations over time for Each Subject",
    x = "Week",
    y = "Observation"
  )           
        
  
```
Overtime, the observations in the control arm have parily constant values while the observations in the exerimental arm seems to be increasing over time. 


##probelm 3



```{r}

sim_t.test = function(n = 30, mu, sigma = 5) {
  
  sim_data = 
    tibble(
      x=rnorm(n = n, mean = mu, sd = sigma)
    )
  
  sim_data %>% 
    summarize (
      mean = mean(x),
      sd = sd(x)
    )
  
  sim_data %>% 
    t.test() %>% 
    broom::tidy()
  
}
```

Testing the fucntion


```{r}
test_results = 
rerun(10, sim_t.test(mu = 0)) %>% 
  bind_rows()
```


Running simulations and putting into dataframe


```{r}
mu_list = 
  list(
    "mu = 0" = 0,
    "mu = 1" = 1,
    "mu = 2" = 2,
    "mu = 3" = 3,
    "mu = 4" = 4,
    "mu = 5" = 5,
    "mu = 6" = 6
    
  )

output = vector("list", length = 7)


for(i in 1:7) {
  output[[i]] = 
    rerun(1000, sim_t.test(mu = mu_list[[i]]))
    
sim_results = bind_rows(output)
}
```

Graphing the results

```{r}
sim_results_df = 
  tibble(
    mu = c(0,1,2,3,4,5,6)
  ) %>% 
  mutate(
    output_lists = map(.x = mu, ~ rerun(100, sim_t.test(mu = .x))),
    estimate_df = map(output_lists, bind_rows)
  ) %>% 
    select(-output_lists) %>% 
    unnest(estimate_df)
```

```{r}

sim_results_df %>%
mutate(reject = ifelse(p.value < '0.05', 1, 0)) %>%

group_by(mu) %>%
summarize(prop_reject = mean(reject)) %>%
ggplot(aes(x = mu, y = prop_reject)) +
geom_point() +
labs(
title = "Proportion of times the null is rejected",
x = "True Value of Mu",
y = "Power")
```


```{r}
sim_results_rej = 
sim_results_df %>%
mutate(reject = ifelse(p.value < '0.05', 1, 0)) %>%
filter(reject == 1) %>% 
group_by(mu) %>%
summarize(mean_mu = mean(estimate)) %>%
  mutate(decision = "rejected")
  

sim_results_all = 
  sim_results_df %>% 
  mutate(reject = ifelse(p.value < '0.05', 1, 0)) %>% 
  group_by(mu) %>% 
  summarize(mean_mu = mean(estimate)) %>% 
  mutate(decision = "all")


ggplot(data = sim_results_all, aes(x = mu, y = mean_mu, color = decision)) + 
  geom_point() + 
  geom_point(data = sim_results_rej) +
  labs(
    title = "True mu vs. Estimated mu",
    x = "True Value of mu",
    y = "Mean Estimated Value of mu")

```

